packages:
  - apps/*
  - packages/*
  - configs/*

autoInstallPeers: true

catalogs:
  biome:
    '@biomejs/biome': ^2.4.13
  express:
    '@types/express': ^5.0.6
  mikro-orm:
    '@mikro-orm/cli': ^6.6.7
    '@mikro-orm/core': ^6.6.7
    '@mikro-orm/migrations': ^6.6.7
    '@mikro-orm/nestjs': ^6.1.1
    '@mikro-orm/postgresql': ^6.6.7
  nestjs:
    '@nestjs/cli': ^11.0.21
    '@nestjs/common': ^11.1.19
    '@nestjs/config': ^4.0.4
    '@nestjs/core': ^11.1.19
    '@nestjs/platform-express': ^11.1.19
    '@nestjs/schematics': ^11.1.0
    '@nestjs/swagger': ^11.4.1
    '@nestjs/terminus': ^11.1.1
    '@nestjs/testing': ^11.1.19
    reflect-metadata: ^0.2.2
    rxjs: ^7.8.2
  rimraf:
    rimraf: ^6.1.3
  supertest:
    '@types/supertest': ^7.2.0
    supertest: ^7.2.2
  swc:
    '@swc/cli': ^0.8.1
    '@swc/core': ^1.15.30
  turbo:
    turbo: ^2.9.6
  typescript:
    '@types/node': ^25.6.0
    source-map-support: ^0.5.21
    ts-loader: ^9.5.7
    ts-node: ^10.9.2
    typescript: ^6.0.3
  vitest:
    '@vitest/coverage-v8': ^4.1.5
    vitest: ^4.1.5

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
